### ISSUE TITLE
About the memory and GPU requirements for running the real dataset

### ISSUE THREAD

**Issue by JachyLikeCoding** [swing-research/Implicit-Cryo-Electron-Tomography#2]
Hi, I'm currently trying to run the settings in real_data_tkiuv.py using the ice-tide method. I have downloaded the tomo2_L1G1.st and tomo2_L1G1.tlt from EMPIAR, then converted the '.st' to '.mrc'. 

However, I'm encountering RAM and GPU memory overflow issues (my computer has 24GB of GPU, 64GB of RAM). Could you please provide an estimate of the minimum memory and GPU memory requirements to successfully run the real dataset?

Thanks a lot!

**Comment by ValentinDebarnot** [comment]
Hi, thank you for your interest!
If memory is an issue, in the config file config/real_data_tkiuv, you can try to reduce the parameters 'nRays' (number of ray to sample), 'batch_set' (batch size) or 'ray_length' (number of point in the ray). By scaling down reasonably these parameters you should be able to use your 24GB GPU.
Also, in the next 2 days, I will upload a new version of the code that simplifies the training and improve significantly the results on this real dataset, so I would suggest to wait for this new release if this is not too much trouble.

Best,
Valentin

**Comment by JachyLikeCoding** [comment]
> Hi, thank you for your interest! If memory is an issue, in the config file config/real_data_tkiuv, you can try to reduce the parameters 'nRays' (number of ray to sample), 'batch_set' (batch size) or 'ray_length' (number of point in the ray). By scaling down reasonably these parameters you should be able to use your 24GB GPU. Also, in the next 2 days, I will upload a new version of the code that simplifies the training and improve significantly the results on this real dataset, so I would suggest to wait for this new release if this is not too much trouble.
> 
> Best, Valentin

Thanks for your reply, I downloaded the latest version. When I trained on real data, I got a failed reconstruction, and I have not figured out why. I guess there's something wrong with the training data I'm using. Could you please provide the required data for this real dataset?

Thank you very much!

**Comment by ValentinDebarnot** [comment]
Thank you again for you comments!
I made the data available, you can find the link and the procedure on the README. The files are rather large (3GB) but once downloaded you should be able to run the code as it is.
On the other side, if you are willing to send me your own tilt-series, I would be happy to give it a shot. You can reach me by email if you want: valentin.debarnot@unibas.ch
