### ISSUE TITLE
Missing libraries in install_ICETIDE.sh

### ISSUE THREAD

**Issue by josedacostafilho** [swing-research/Implicit-Cryo-Electron-Tomography#4]
Hello, first of all congratulations for this amazing work. I have been trying to make Ice-Tide work on my setup, and was only able to when I further installed the following libraries (which were not included in the install script):

numpy 1.23.4 (this is the newest version which does not lead to conflicts with odl)
bm3d
astra-toolbox
pandas

I know the code is still under development, but I thought this feedback would be appreciated by the team.

**Comment by ValentinDebarnot** [comment]
Dear josedacostafilho, 
Thank you for reporting that and thank you for your comments. I will update that very soon!
Best,
Valentin
